<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Force database installation</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database initialization in progress</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "demodb";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname + ";create=true", "user", "pwd");
            Statement stmt = con.createStatement();
            
            try {
                stmt.execute("CREATE SCHEMA " + dbname);
                // schema was created; it will appear into: Other schemas -> "dbname"
            } catch (SQLException e) { 
                // schema already exists; do nothing.
            }
            
            /* drop tables if they exist */
            String tablenames[] = new String[] {
                "comanda","oferta","usuari",
            };
            for (String tablename : tablenames) {
                try { 
                    stmt.executeUpdate("DROP TABLE " + dbname + "." + tablename); 
                    out.println("<pre> -> DROP TABLE " + dbname + "." + tablename + "<pre>");
                } catch (SQLException e) { 
                    // table didn't exist; it is the first time
                }
            }
            
            /* creating tables */
            String tables[] = new String[] {
                "CREATE TABLE " + dbname + ".usuari (" +
                    " alias VARCHAR(10) PRIMARY KEY NOT NULL," + " contrasenya VARCHAR(10) NOT NULL,"+
                    " nom VARCHAR(20) NOT NULL,"+"cognom1 VARCHAR(12) NOT NULL,"+"cognom2 VARCHAR(12),"+"adreça VARCHAR(50) NOT NULL,"+"telefon CHAR(9),"+"email VARCHAR(50) NOT NULL,"+"data_naix DATE NOT NULL)",
                "CREATE TABLE " + dbname + ".comanda (" +
                    " id_comanda INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," + 
                    " id_usuari VARCHAR(10),"+"id_oferta INT NOT NULL,"+"preu_total FLOAT NOT NULL,"+"personas INT NOT NULL,"+"data DATE NOT NULL,"+"hora TIME NOT NULL)",
                "CREATE TABLE " + dbname + ".oferta (" +
                    " oferta_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," + 
                    " titol_oferta VARCHAR(50) NOT NULL,"+"descripcio VARCHAR(500) NOT NULL,"+"places_disp INT NOT NULL,"+"preu_pers FLOAT NOT NULL,"+"desti VARCHAR(20) NOT NULL,"+"data_sortida DATE NOT NULL,"+"data_tornada DATE NOT NULL,"+"dies_estada INT NOT NULL)"
                    ,
                "ALTER TABLE " + dbname + ".comanda ADD CONSTRAINT fk_usuari FOREIGN KEY (id_usuari) REFERENCES " + dbname + ".usuari (alias) ON DELETE CASCADE",
                "ALTER TABLE " + dbname + ".comanda ADD CONSTRAINT fk_oferta FOREIGN KEY (id_oferta) REFERENCES " + dbname + ".oferta (oferta_id) ON DELETE CASCADE",
            };
            for (String table : tables) {
                try {
                    stmt.execute(table);
                } catch(SQLException e) {
                    out.println("<span class='error'>Error creating table: " + table + "</span>");
                    return;
                }
                out.println("<pre> -> " + table + "<pre>");
            }
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
               "INSERT INTO " + dbname + ".usuari(alias,contrasenya,nom,cognom1,cognom2,adreça,telefon,email,data_naix) VALUES ('ALIAS123','ALIAS123','RODOLFO','BERTRÁN','MORENO','C/ MOLL DE LLEVANT NÚM. 5','911548922','rodolfo@gmail.com','1995-01-28'),('sob','sob','Sistemes','Oberts','','AV. Mª FORTUNY NÚM. 7, 4º 5ª','914556130','sistemesoberts@urv.cat','1995-01-07'),('ANONYMOUS','123456789','JOSÉ','GALDO','HUERTAS','PLAÇA MERCADAL, 3, ÀTIC 3ª','977794879','galdo_90@hotmail.com','1990-04-19')",
               "INSERT INTO " + dbname + ".oferta(titol_oferta,descripcio,places_disp,preu_pers,desti,data_sortida,data_tornada,dies_estada) VALUES ('VIAJE A DUBAI','EL VIAJE INCLUYE: TRANSPORTE EN UN MAGNIFICO YATE, DESAYUNO, COMIDA Y CENA TODO DENTRO DE UN FASCINANTE BUFFET, ESTANCIA DE 7 DÍAS EN EL HOTEL ROYAL PARK DE DUBAI Y VUELTA EN UN VUELO DE FLY EMIRATES EN PRIMERA CLASE',7,1832,'DUBAI','2016-12-09','2016-12-16',7),('VIAJE A BERLIN','EL VIAJE INCLUYE: TRANSPORTE EN UN AVIÓN DE LA COMPAÑIA DE RYANAIR EN CLASE TURISTA, ESTANCIA DE 3 DÍAS EN HOTEL DE 3 ESTRELLAS CON MEDIA PENSIÓN VUELTA EN AVIÓN DE FLY EMIRATES EN CLASE TURISTA',89,322,'BERLIN','2016-12-26','2016-12-29',3)",
               "INSERT INTO " + dbname + ".comanda(id_usuari,id_oferta,preu_total,personas,data,hora) VALUES ('ALIAS123',1,3664,2,'2016-05-12','18:03:22'),('sob',2,1288,4,'2016-05-13','10:41:44'),('ANONYMOUS',2,644,2,'2016-05-13','21:33:04'),('ANONYMOUS',1,3664,2,'2016-05-13','17:10:00')",
                /* primero insertar usuario, luego oferta y luego pedido*/
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
