<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Force database installation</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database initialization in progress</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "demodb";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname + ";create=true", "user", "pwd");
            Statement stmt = con.createStatement();
            
            try {
                stmt.execute("CREATE SCHEMA " + dbname);
                // schema was created; it will appear into: Other schemas -> "dbname"
            } catch (SQLException e) { 
                // schema already exists; do nothing.
            }
            
            /* drop tables if they exist */
            String tablenames[] = new String[] {
                "comanda","oferta","usuari",
            };
            for (String tablename : tablenames) {
                try { 
                    stmt.executeUpdate("DROP TABLE " + dbname + "." + tablename); 
                    out.println("<pre> -> DROP TABLE " + dbname + "." + tablename + "<pre>");
                } catch (SQLException e) { 
                    // table didn't exist; it is the first time
                }
            }
            
            /* creating tables */
            String tables[] = new String[] {
                "CREATE TABLE " + dbname + ".usuari (" +
                    " alias VARCHAR(10) PRIMARY KEY NOT NULL," + " contrasenya VARCHAR(50) NOT NULL,"+
                    " nom VARCHAR(20) NOT NULL,"+"cognom1 VARCHAR(12) NOT NULL,"+"cognom2 VARCHAR(12),"+"adreça VARCHAR(50) NOT NULL,"+"telefon CHAR(9),"+"email VARCHAR(50) NOT NULL,"+"data_naix DATE NOT NULL)",
                "CREATE TABLE " + dbname + ".comanda (" +
                    " id_comanda INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," + 
                    " id_usuari VARCHAR(10),"+"id_oferta INT NOT NULL,"+"preu_total FLOAT NOT NULL,"+"personas INT NOT NULL,"+"data DATE NOT NULL,"+"hora TIME NOT NULL)",
                "CREATE TABLE " + dbname + ".oferta (" +
                    " oferta_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," + 
                    " titol_oferta VARCHAR(50) NOT NULL,"+"descripcio VARCHAR(500) NOT NULL,"+"places_disp INT NOT NULL,"+"preu_pers FLOAT NOT NULL,"+"desti VARCHAR(20) NOT NULL,"+"data_sortida DATE NOT NULL,"+"data_tornada DATE NOT NULL,"+"dies_estada INT NOT NULL)"
                    ,
                "ALTER TABLE " + dbname + ".comanda ADD CONSTRAINT fk_usuari FOREIGN KEY (id_usuari) REFERENCES " + dbname + ".usuari (alias) ON DELETE CASCADE",
                "ALTER TABLE " + dbname + ".comanda ADD CONSTRAINT fk_oferta FOREIGN KEY (id_oferta) REFERENCES " + dbname + ".oferta (oferta_id) ON DELETE CASCADE",
            };
            for (String table : tables) {
                try {
                    stmt.execute(table);
                } catch(SQLException e) {
                    out.println("<span class='error'>Error creating table: " + table + "</span>");
                    return;
                }
                out.println("<pre> -> " + table + "<pre>");
            }
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
               "INSERT INTO " + dbname + ".usuari(alias,contrasenya,nom,cognom1,cognom2,adreça,telefon,email,data_naix) VALUES ('ALIAS123','a951cd546abec48ae8b008168d1e35a29a076617','RODOLFO','BERTRÁN','MORENO','C/ MOLL DE LLEVANT NÚM. 5','911548922','rodolfo@gmail.com','1995-01-28'),('sob','0e767424cc0db25e878624a6ab798885abe2043e','Sistemes','Oberts','','AV. Mª FORTUNY NÚM. 7, 4º 5ª','914556130','sistemesoberts@urv.cat','1995-01-07'),('ANONYMOUS','f7c3bc1d808e04732adf679965ccc34ca7ae3441','JOSÉ','GALDO','HUERTAS','PLAÇA MERCADAL, 3, ÀTIC 3ª','977794879','galdo_90@hotmail.com','1990-04-19')",
               "INSERT INTO " + dbname + ".oferta(titol_oferta,descripcio,places_disp,preu_pers,desti,data_sortida,data_tornada,dies_estada) VALUES ('VIATGE A DUBAI','El viajte inclou transport en un magnífic iot, esmorzar, menjar i dinar tot dins un fascinant buffet estància de 7 dies a Hotel Royal Park de Dubai i tornada en un vol de Fly Emirates en primera classe.',7,1832.6,'Dubai','2016-12-09','2016-12-16',7),('VIATGE A BERLIN','El viajte inclou transport en avió, amb Ryanair a classe turista estancia de 3 dies en un hotel de 3 estrelles amb mitja pensió, tornada en avió de Fly Emirates classe turista.',89,322,'Berlin','2016-12-26','2016-12-29',3),('VIATGE A PARIS','El viajte inclou esmorzar, menjar i dinar, anada i tornada en classe turista en vols de Ryanair i estància a Hotel Tokyo Star de Paris.',9,469.95,'Paris','2017-01-09','2016-01-13',4),('VIATGE A COPENHAGUE','El viajte inclou transport en un magnífic iot, esmorzar, menjar i dinar tot dins un fascinant buffet estància de 9 dies a Hotel Royal Park i tornada en un vol de Fly Emirates en primera classe.',2,3450.76,'Copenhague','2017-08-19','2016-08-28',9),('VIATGE A LONDRES','El viajte inclou transport en avió, amb Ryanair a classe turista estancia de 14 dies en un hotel de 3 estrelles amb mitja pensió, tornada en avió de Fly Emirates classe turista.',89,1556,'Londres','2017-11-15','2017-11-29',14),('VIATGE A MOSCU','El viajte inclou esmorzar, menjar i dinar, anada i tornada en classe turista en vols de Ryanair i estància a Hotel Tokyo Star de Moscu.',44,999.65,'Moscu','2017-03-09','2016-03-13',4),('VIATGE A VARSOVIA','El viajte inclou transport en un magnífic iot, esmorzar, menjar i dinar tot dins un fascinant buffet estància de 12 dies a Hotel Royal Park de Varsovia i tornada en un vol de Fly Emirates en primera classe.',99,2000,'Varsovia','2017-04-09','2017-12-21',12),('VIATGE A HAMBURG','El viajte inclou transport en avió, amb Ryanair a classe turista estancia de 3 dies en un hotel de 3 estrelles amb mitja pensió, tornada en avió de Fly Emirates classe turista.',229,702,'Hamburg','2016-12-30','2017-01-1',3),('VIATGE A MONACO','El viajte inclou esmorzar, menjar i dinar, anada i tornada en classe turista en vols de Ryanair i estància a Hotel Rey Carlos de Monaco.',84,999,'Monaco','2017-05-09','2016-05-13',4)",
               "INSERT INTO " + dbname + ".comanda(id_usuari,id_oferta,preu_total,personas,data,hora) VALUES ('ALIAS123',1,3664,2,'2016-05-12','18:03:22'),('sob',2,1288,4,'2016-05-13','10:41:44'),('ANONYMOUS',2,644,2,'2016-05-13','21:33:04'),('ANONYMOUS',1,3664,2,'2016-05-13','17:10:00')",
                /* primero insertar usuario, luego oferta y luego pedido*/
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
