<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Force database installation</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database initialization in progress</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "demodb";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname + ";create=true", "user", "pwd");
            Statement stmt = con.createStatement();
            
            try {
                stmt.execute("CREATE SCHEMA " + dbname);
                // schema was created; it will appear into: Other schemas -> "dbname"
            } catch (SQLException e) { 
                // schema already exists; do nothing.
            }
            
            /* drop tables if they exist */
            String tablenames[] = new String[] {
                "comanda","oferta","usuari",
            };
            for (String tablename : tablenames) {
                try { 
                    stmt.executeUpdate("DROP TABLE " + dbname + "." + tablename); 
                    out.println("<pre> -> DROP TABLE " + dbname + "." + tablename + "<pre>");
                } catch (SQLException e) { 
                    // table didn't exist; it is the first time
                }
            }
            
            /* creating tables */
            String tables[] = new String[] {
                "CREATE TABLE " + dbname + ".usuari (" +
                    " alias VARCHAR(10) PRIMARY KEY NOT NULL," + " contrasenya VARCHAR(50) NOT NULL,"+
                    " nom VARCHAR(50) NOT NULL,"+"cognom1 VARCHAR(50) NOT NULL,"+"cognom2 VARCHAR(50),"+"adreça VARCHAR(50) NOT NULL,"+"telefon CHAR(9),"+"email VARCHAR(50) NOT NULL,"+"data_naix DATE NOT NULL,"+"sexe VARCHAR(5) NOT NULL)",
                "CREATE TABLE " + dbname + ".comanda (" +
                    " id_comanda INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," + 
                    " id_usuari VARCHAR(10),"+"id_oferta INT NOT NULL,"+"preu_total FLOAT NOT NULL,"+"personas INT NOT NULL,"+"data DATE NOT NULL,"+"hora TIME NOT NULL)",
                "CREATE TABLE " + dbname + ".oferta (" +
                    " oferta_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," + 
                    " titol_oferta VARCHAR(50) NOT NULL,"+"descripcio VARCHAR(500) NOT NULL,"+"places_disp INT NOT NULL,"+"preu_pers FLOAT NOT NULL,"+"desti VARCHAR(20) NOT NULL,"+"data_sortida DATE NOT NULL,"+"data_tornada DATE NOT NULL,"+"dies_estada INT NOT NULL,"+"descripcio_gran VARCHAR(800) NOT NULL)"
                    ,
                "ALTER TABLE " + dbname + ".comanda ADD CONSTRAINT fk_usuari FOREIGN KEY (id_usuari) REFERENCES " + dbname + ".usuari (alias) ON DELETE CASCADE",
                "ALTER TABLE " + dbname + ".comanda ADD CONSTRAINT fk_oferta FOREIGN KEY (id_oferta) REFERENCES " + dbname + ".oferta (oferta_id) ON DELETE CASCADE",
            };
            for (String table : tables) {
                try {
                    stmt.execute(table);
                } catch(SQLException e) {
                    out.println("<span class='error'>Error creating table: " + table + "</span>");
                    return;
                }
                out.println("<pre> -> " + table + "<pre>");
            }
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
               "INSERT INTO " + dbname + ".usuari(alias,contrasenya,nom,cognom1,cognom2,adreça,telefon,email,data_naix,"
                    + "sexe) VALUES ('ALIAS123','a951cd546abec48ae8b008168d1e35a29a076617','RODOLFO','BERTRÁN','MORENO',"
                    + "'C/ MOLL DE LLEVANT NÚM. 5','911548922','rodolfo@gmail.com','1995-01-28','Home'),('sob','0e767424c"
                    + "c0db25e878624a6ab798885abe2043e','Sistemes','Oberts','','AV. Mª FORTUNY NÚM. 7, 4º 5ª','914556130',"
                    + "'sistemesoberts@urv.cat','1995-01-07','Home'),('ANONYMOUS','f7c3bc1d808e04732adf679965ccc34ca7ae3441'"
                    + ",'MARIA','GALDO','HUERTAS','PLAÇA MERCADAL, 3, ÀTIC 3ª','977794879','galdo_90@hotmail.com','1990-04-19','Dona')",
               "INSERT INTO " + dbname + ".oferta(titol_oferta,descripcio,places_disp,preu_pers,desti,data_sortida,"
                    + "data_tornada,dies_estada,descripcio_gran) VALUES ('VIATGE A DUBAI','El viatge inclou transport en un magnífic"
                    + " iot, esmorzar, menjar i dinar tot dins un fascinant buffet estància de 7 dies a Hotel Royal "
                    + "Park de Dubai i tornada en un vol de Fly Emirates en primera classe.',7,1832.6,'Dubai','2016-12-09',"
                    + "'2016-12-15',7,'El viatge inclou transport en un magnífic iot, esmorzar, menjar i dinar tot dins un "
                    + "fascinant buffet estància de 7 dies a Hotel Royal Park de Dubai i tornada en un vol de Fly Emirates "
                    + "en primera classe. Visites al museu nacional de Dubai i al parc nacional de Dubai, a més visitarem el "
                    + "nou rascacel Dubai Star, construït pel señor Calatraba, un arquitecte de prestigi a nivell internacional"
                    + " i nascut a Espanya. D''altra banda hi han activitats lúdiques, podrem anar al pub The best, al parc d''atraccions"
                    + " Dubai''s park entre d''altres activitats.'),('VIATGE A BERLIN','El viatge inclou transport en avió, amb Ryanair a classe turista "
                    + "estancia de 3 dies en un hotel de 3 estrelles amb mitja pensió, tornada en avió de Fly Emirates classe "
                    + "turista.',89,322,'Berlin','2016-12-26','2016-12-28',3,'El viatge inclou transport en avió, amb Ryanair a"
                    + " classe turista estancia de 3 dies en un hotel de 3 estrelles amb mitja pensió, tornada en avió de Fly "
                    + "Emirates classe turista. Podrem visitar monuments del III reich, tindrem la oportunitat de veure el camp "
                    + "de fútbol de l''Hertha de Berlin i el partir Hertha Berlin - Borussia Dortmund. El viatge a més inclou el "
                    + "concert de David Bustamante al Olympiastadion de Berlin i una camiseta dedicada pel mateix cantant. Berlin "
                    + "és una ciutat molt bonica, la capital de Alemanya.'),('VIATGE A PARIS','El viatge inclou esmorzar, menjar "
                    + "i dinar, anada i tornada en classe turista en vols de Ryanair i estància a Hotel Tokyo Star de Paris.',9,469.95,'Paris',"
                    + "'2017-01-09','2017-01-13',4,'El viatge inclou esmorzar, menjar i dinar, anada i tornada en classe turista en vols de Ryanair"
                    + " i estància a Hotel Tokyo Star de Paris. A més pels nens petits que viatgen en familia visitarem el Parc Disneyland on totes "
                    + "les nostres ilusions són realitat, i aquell mateix día el sopar estarà inclòs en un fabulòs restaurant de Paris, Quatre formatgi, "
                    + "per a sopar menjar italià de primera qualitat.'),('VIATGE A COPENHAGUE','El viatge inclou transport en un magnífic iot, esmorzar, menjar i "
                    + "dinar tot dins un fascinant buffet estància de 9 dies a Hotel Royal Park i tornada en un vol de Fly Emirates en "
                    + "primera classe.',2,3450.76,'Copenhague','2017-08-19','2017-08-27',9,'El viatje inclou transport en un magnífic iot, "
                    + "esmorzar, menjar i dinar tot dins un fascinant buffet estància de 9 dies a Hotel Royal Park i tornada en un vol de "
                    + "Fly Emirates en primera classe. Les terres daneses són un bon lloc on anar a pasar una estada amb tota la familia, "
                    + "la naturalesa és la seva característica general, i el viatje inclou unes quantes excursions a llocs inimaginables.'),"
                    + "('VIATGE A LONDRES','El viatge inclou transport "
                    + "en avió, amb Ryanair a classe turista estancia de 14 dies en un hotel de 3 estrelles amb mitja pensió, tornada en "
                    + "avió de Fly Emirates classe turista.',89,1556,'Londres','2017-11-15','2017-11-28',14,'El viatge inclou transport en avió, amb Ryanair a classe "
                    + "turista estancia de 14 dies en un hotel de 3 estrelles amb mitja pensió, tornada en avió de Fly Emirates classe "
                    + "turista. Podrem veure el Big Ben que és segurament el rellotge més famòs del món, i si t''agrada el fútbol podràs "
                    + "visitar camps com l''Emirate Stadium, Stamford Bridge... Londres és una ciutat que té una bellesa arquitectònica"
                    + " juntament amb les innovacions del segle 21.'),('VIATGE A MOSCU','El viatge "
                    + "inclou esmorzar, menjar i dinar, anada i tornada en classe turista en vols de Ryanair i estància a Hotel Tokyo Star "
                    + "de Moscu.',44,999.65,'Moscu','2017-03-09','2017-03-12',4,'El viatge inclou esmorzar, menjar i dinar, anada i tornada en"
                    + " classe turista en vols de Ryanair i estància a Hotel Tokyo Star de Moscu. Podrem visitar edificis emblemàtics de Moscu"
                    + " com el Kremlin de Moscu, la Catedral de San Basili, Mausoleo de Lenin i la Catedral de la Dormició. Tot això amb busos "
                    + "turístics, amb lo que no hauràs de patir per res.'),('VIATGE A VARSOVIA','El viatge inclou transport en un magní"
                    + "fic iot, esmorzar, menjar i dinar tot dins un fascinant buffet estància de 12 dies a Hotel Royal Park de Varsovia i "
                    + "tornada en un vol de Fly Emirates en primera classe.',99,2000,'Varsovia','2017-04-09','2017-04-20',12,'El viatge inclou"
                    + " transport en un magnífic iot, esmorzar, menjar i dinar tot dins un fascinant buffet estància de 12 dies a Hotel Royal "
                    + "Park de Varsovia i tornada en un vol de Fly Emirates en primera classe. Varsovia és una capital en expansió a nivell"
                    + " tecnològic, i amb una naturalesa molt elegeant que l''envolta, el lloc ideal si volem estar tranquils i en familia però"
                    + " en una gran ciutat.'),('VIATGE A HAMBURG','El viatge inclou transport en avió, amb Ryanair a classe turista estancia de 3 dies en un hotel de 3 estre"
                    + "lles amb mitja pensió, tornada en avió de Fly Emirates classe turista.',229,702,'Hamburg','2016-12-30','2017-01-01',3,'El viatge inclou transport en avió,"
                    + " amb Ryanair a classe turista estancia de 3 dies en un hotel de 3 estrelles amb mitja pensió, tornada en avió de Fly Emirates classe turista. Hamburg és un"
                    + " lloc turístic molt visitat, que engloba lo millor d''Alemanya on no poden faltar bars per a servir una cervesa exquisita.'),"
                    + "('VIATGE A MONACO','El viatge inclou esmorzar, menjar i dinar, anada i tornada en classe turista en vols de Ryanair"
                    + " i estància a Hotel Rey Carlos de Monaco.',84,999,'Monaco','2017-05-09','2017-05-12',4,'El viatge inclou esmorzar, menjar"
                    + " i dinar, anada i tornada en classe turista en vols de Ryanair i estància a Hotel Rey Carlos de Monaco. Els carrers d''aquesta"
                    + " ciutat tenen molta història, entre d''altres aquests carrers formen el GP de Monaco, un Gran Premi de Fòrmula 1 molt famos que"
                    + " podràs disfrutar en directe aquests dies.')",
               "INSERT INTO " + dbname + ".comanda(id_usuari,id_oferta,preu_total,personas,data,hora) VALUES ('ALIAS123',1,3664,2,'2016-05-12','18:03:22'),('sob',2,1288,4,'2016-05-13','10:41:44'),('ANONYMOUS',2,644,2,'2016-05-13','21:33:04'),('ANONYMOUS',1,3664,2,'2016-05-13','17:10:00')",
                /* primero insertar usuario, luego oferta y luego pedido*/
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
